source:
  api_url: "https://yts.torrentbay.to/api/v2/list_movies.json?page={}&limit=50"
  cast_url: "https://www.imdb.com/title/{}/fullcredits"

tracking:
  meta_path: 'meta.json'

logging:
  file_name: 'track.log'
  format: '%(asctime)s:%(levelname)s:%(message)s'
  level: INFO
  handlers:
      [
        logging.FileHandler("track.log"),
        logging.StreamHandler(sys.stdout)
    ]
